<?php

return [
    'meta' => [
        'template_key' => 'engine_4d34t_s64029_cantereuro2',
        'template_version' => 'v1',
        'source_excel' => 'Parts Labour Engine 4D34T-S64029 Canter Euro 2.xlsx',
        'rows_count' => 96
    ],
    'rows' => [
        [
            'qty' => '1',
            'uom' => 'set',
            'part_number' => 'ME999384',
            'part_description' => 'Main Bearing (Metal Duduk)',
            'part_section' => '',
            'purchase_price' => '390000',
            'total' => '390000',
            'sales_price' => '533925',
            'extended_price' => '533925',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'set',
            'part_number' => 'ME996566',
            'part_description' => 'ring piston',
            'part_section' => '',
            'purchase_price' => '1125000',
            'total' => '1125000',
            'sales_price' => '1483125',
            'extended_price' => '1483125',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'set',
            'part_number' => 'ME995153',
            'part_description' => 'Con rod Bearing (Metal Jalan)',
            'part_section' => '',
            'purchase_price' => '325000',
            'total' => '325000',
            'sales_price' => '658508',
            'extended_price' => '658508',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'set',
            'part_number' => 'ME215092W',
            'part_description' => 'seal ValveSeal Klep',
            'part_section' => '',
            'purchase_price' => '420000',
            'total' => '420000',
            'sales_price' => '676305',
            'extended_price' => '676305',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME227518',
            'part_description' => 'Gasket cyl Haed/Pak Kop',
            'part_section' => '',
            'purchase_price' => '350000',
            'total' => '350000',
            'sales_price' => '587318',
            'extended_price' => '587318',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME017208W',
            'part_description' => 'Seal Crankshft Fr',
            'part_section' => '',
            'purchase_price' => '145000',
            'total' => '145000',
            'sales_price' => '311456',
            'extended_price' => '311456',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME011754W',
            'part_description' => 'Seal Crankshaft Rr',
            'part_section' => '',
            'purchase_price' => '450000',
            'total' => '450000',
            'sales_price' => '1005559',
            'extended_price' => '1005559',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'set',
            'part_number' => 'ME994312',
            'part_description' => 'Gasket kit/Paking SET',
            'part_section' => '',
            'purchase_price' => '1390000',
            'total' => '1390000',
            'sales_price' => '2491650',
            'extended_price' => '2491650',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '3',
            'uom' => 'ea',
            'part_number' => 'ME013560',
            'part_description' => 'Thrust washer (Metal bulan)',
            'part_section' => '',
            'purchase_price' => '245000',
            'total' => '735000',
            'sales_price' => '400444',
            'extended_price' => '1201332',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME11895A',
            'part_description' => 'Camshaft',
            'part_section' => '',
            'purchase_price' => '2150000',
            'total' => '2150000',
            'sales_price' => '5220600',
            'extended_price' => '5220600',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'set',
            'part_number' => 'ME220470',
            'part_description' => 'Piston (4 pcs)',
            'part_section' => '',
            'purchase_price' => '4100000',
            'total' => '4100000',
            'sales_price' => '6407100',
            'extended_price' => '6407100',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '4',
            'uom' => 'ea',
            'part_number' => 'ME013320',
            'part_description' => 'Pin piston',
            'part_section' => '',
            'purchase_price' => '170000',
            'total' => '680000',
            'sales_price' => '288150',
            'extended_price' => '1152600',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '8',
            'uom' => 'ea',
            'part_number' => 'ME012966',
            'part_description' => 'Snap Ring',
            'part_section' => '',
            'purchase_price' => '60000',
            'total' => '480000',
            'sales_price' => '87000',
            'extended_price' => '696000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME017484',
            'part_description' => 'Oil Pump',
            'part_section' => '',
            'purchase_price' => '2200000',
            'total' => '2200000',
            'sales_price' => '8008875',
            'extended_price' => '8008875',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME013307',
            'part_description' => 'Oil Filter',
            'part_section' => '',
            'purchase_price' => '105000',
            'total' => '105000',
            'sales_price' => '177975',
            'extended_price' => '177975',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME035829',
            'part_description' => 'Fuel Filter',
            'part_section' => '',
            'purchase_price' => '70000',
            'total' => '70000',
            'sales_price' => '106785',
            'extended_price' => '106785',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'set',
            'part_number' => 'ME013366',
            'part_description' => 'Liner  (4 Pcs)',
            'part_section' => '',
            'purchase_price' => '800000',
            'total' => '800000',
            'sales_price' => '1423800',
            'extended_price' => '1423800',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'MS556007',
            'part_description' => 'Bearing front cover (6207 2RS)',
            'part_section' => '',
            'purchase_price' => '75000',
            'total' => '75000',
            'sales_price' => '160178',
            'extended_price' => '160178',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'TE0500103/ME664683',
            'part_description' => 'Water Pump',
            'part_section' => '',
            'purchase_price' => '665000',
            'total' => '665000',
            'sales_price' => '1483125',
            'extended_price' => '1483125',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '3',
            'uom' => 'ea',
            'part_number' => 'MF407010',
            'part_description' => 'Stud exhaust',
            'part_section' => '',
            'purchase_price' => '195000',
            'total' => '585000',
            'sales_price' => '47460',
            'extended_price' => '142380',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME028398',
            'part_description' => 'Vacuum pump (Vacuum Blower)',
            'part_section' => '',
            'purchase_price' => '1450000',
            'total' => '1450000',
            'sales_price' => '5517225',
            'extended_price' => '5517225',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'set',
            'part_number' => 'MH014025',
            'part_description' => 'V Belt',
            'part_section' => '',
            'purchase_price' => '55000',
            'total' => '55000',
            'sales_price' => '100853',
            'extended_price' => '100853',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME999555',
            'part_description' => 'Thermostat',
            'part_section' => '',
            'purchase_price' => '125000',
            'total' => '125000',
            'sales_price' => '533925',
            'extended_price' => '533925',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => 'ML242056',
            'part_description' => 'mounting engine',
            'part_section' => '',
            'purchase_price' => '150000',
            'total' => '300000',
            'sales_price' => '169500',
            'extended_price' => '339000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME017115',
            'part_description' => 'gear crankshaft',
            'part_section' => '',
            'purchase_price' => '650000',
            'total' => '650000',
            'sales_price' => '734500',
            'extended_price' => '734500',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'TE0500105',
            'part_description' => 'front cover housing',
            'part_section' => '',
            'purchase_price' => '2600000',
            'total' => '2600000',
            'sales_price' => '4800000',
            'extended_price' => '4800000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => 'ME011660W',
            'part_description' => 'Seal Cover Valve / Seal canter',
            'part_section' => '',
            'purchase_price' => '30000',
            'total' => '60000',
            'sales_price' => '33900',
            'extended_price' => '67800',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME 5211181DN',
            'part_description' => 'Diagfram clutch (Matahari)',
            'part_section' => '',
            'purchase_price' => '1470000',
            'total' => '1470000',
            'sales_price' => '3678150',
            'extended_price' => '3678150',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'Ea',
            'part_number' => '1250A015',
            'part_description' => 'Cap Oil Filler',
            'part_section' => '',
            'purchase_price' => '180000',
            'total' => '180000',
            'sales_price' => '237300',
            'extended_price' => '237300',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'set',
            'part_number' => '6204 2RS',
            'part_description' => 'Bearing Fly Wheel (Roda Gila)',
            'part_section' => '',
            'purchase_price' => '40000',
            'total' => '40000',
            'sales_price' => '110000',
            'extended_price' => '110000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'TE0500146',
            'part_description' => 'Gear camshaft',
            'part_section' => '',
            'purchase_price' => '550000',
            'total' => '550000',
            'sales_price' => '1186500',
            'extended_price' => '1186500',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME015113',
            'part_description' => 'Idler Gear',
            'part_section' => '',
            'purchase_price' => '1100000',
            'total' => '1100000',
            'sales_price' => '2429500',
            'extended_price' => '2429500',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => 'ME013726',
            'part_description' => 'Ring Seal (Elbow Exhaust)',
            'part_section' => '',
            'purchase_price' => '90000',
            'total' => '180000',
            'sales_price' => '135000',
            'extended_price' => '270000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME736904',
            'part_description' => 'Gear FIP',
            'part_section' => '',
            'purchase_price' => '3150000',
            'total' => '3150000',
            'sales_price' => '5650000',
            'extended_price' => '5650000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'DNY-CF-FE71',
            'part_description' => 'Fan Radiator/Kipas Radiator',
            'part_section' => '',
            'purchase_price' => '165000',
            'total' => '165000',
            'sales_price' => '293800',
            'extended_price' => '293800',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => 'ME132005',
            'part_description' => 'Gasket Engine Oil Cooler',
            'part_section' => '',
            'purchase_price' => '9500',
            'total' => '19000',
            'sales_price' => '53393',
            'extended_price' => '106786',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '8',
            'uom' => 'ea',
            'part_number' => 'ME017459',
            'part_description' => 'Valve Cap/Topi Klep',
            'part_section' => '',
            'purchase_price' => '65000',
            'total' => '520000',
            'sales_price' => '73450',
            'extended_price' => '587600',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '4',
            'uom' => 'ea',
            'part_number' => 'ME029006',
            'part_description' => 'Valve Intake',
            'part_section' => '',
            'purchase_price' => '80000',
            'total' => '320000',
            'sales_price' => '210000',
            'extended_price' => '840000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '4',
            'uom' => 'ea',
            'part_number' => 'ME029007',
            'part_description' => 'Valve Exhaust',
            'part_section' => '',
            'purchase_price' => '80000',
            'total' => '320000',
            'sales_price' => '210000',
            'extended_price' => '840000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '4',
            'uom' => 'ea',
            'part_number' => 'ME013297',
            'part_description' => 'Seat Valve In',
            'part_section' => '',
            'purchase_price' => '75000',
            'total' => '300000',
            'sales_price' => '116000',
            'extended_price' => '464000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '4',
            'uom' => 'ea',
            'part_number' => 'ME013188',
            'part_description' => 'Seat Valve Ext',
            'part_section' => '',
            'purchase_price' => '75000',
            'total' => '300000',
            'sales_price' => '116000',
            'extended_price' => '464000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME017354W',
            'part_description' => 'Crankhaft',
            'part_section' => '',
            'purchase_price' => '6300000',
            'total' => '6300000',
            'sales_price' => '',
            'extended_price' => '',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME013364',
            'part_description' => 'Spring Relief',
            'part_section' => '',
            'purchase_price' => '71000',
            'total' => '71000',
            'sales_price' => '135000',
            'extended_price' => '135000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME011279',
            'part_description' => 'Gasket Rocker Cover',
            'part_section' => '',
            'purchase_price' => '35000',
            'total' => '35000',
            'sales_price' => '115000',
            'extended_price' => '115000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '3',
            'uom' => 'ea',
            'part_number' => '90031-16069',
            'part_description' => 'Bolt Manifold /Stud',
            'part_section' => '',
            'purchase_price' => '30000',
            'total' => '90000',
            'sales_price' => '',
            'extended_price' => '',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME014388',
            'part_description' => 'Selang Ventilasi Oil',
            'part_section' => '',
            'purchase_price' => '150000',
            'total' => '150000',
            'sales_price' => '',
            'extended_price' => '',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME011895',
            'part_description' => 'Camshaft',
            'part_section' => '',
            'purchase_price' => '2150000',
            'total' => '2150000',
            'sales_price' => '5220000',
            'extended_price' => '5220000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '4',
            'uom' => 'ea',
            'part_number' => 'ME031888',
            'part_description' => 'Valve Guide EX',
            'part_section' => '',
            'purchase_price' => '40000',
            'total' => '160000',
            'sales_price' => '770000',
            'extended_price' => '3080000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '4',
            'uom' => 'ea',
            'part_number' => 'ME031886',
            'part_description' => 'Valve Guide IN',
            'part_section' => '',
            'purchase_price' => '40000',
            'total' => '160000',
            'sales_price' => '770000',
            'extended_price' => '3080000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME017240',
            'part_description' => 'Oil Seal Slinger CS',
            'part_section' => '',
            'purchase_price' => '216000',
            'total' => '216000',
            'sales_price' => '320000',
            'extended_price' => '320000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'MC844972',
            'part_description' => 'Gauge Unit Temp',
            'part_section' => '',
            'purchase_price' => '907000',
            'total' => '907000',
            'sales_price' => '1320000',
            'extended_price' => '1320000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME225075',
            'part_description' => 'Pipe Vacum',
            'part_section' => '',
            'purchase_price' => '109000',
            'total' => '109000',
            'sales_price' => '260000',
            'extended_price' => '260000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'MC859062',
            'part_description' => 'Switch Engine Pressure',
            'part_section' => '',
            'purchase_price' => '760000',
            'total' => '760000',
            'sales_price' => '940000',
            'extended_price' => '940000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME994676',
            'part_description' => 'Bolt Drain Plug',
            'part_section' => '',
            'purchase_price' => '465000',
            'total' => '465000',
            'sales_price' => '720000',
            'extended_price' => '720000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME013359',
            'part_description' => 'Valve Oil Cooler',
            'part_section' => '',
            'purchase_price' => '244000',
            'total' => '244000',
            'sales_price' => '475000',
            'extended_price' => '475000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 3117546100,
            'part_description' => 'Benjo (Eye Bolt)',
            'part_section' => '',
            'purchase_price' => '65000',
            'total' => '65000',
            'sales_price' => '123000',
            'extended_price' => '123000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME016571',
            'part_description' => 'Cap Fuel Return',
            'part_section' => '',
            'purchase_price' => '75000',
            'total' => '75000',
            'sales_price' => '165000',
            'extended_price' => '165000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => 'ME702236',
            'part_description' => 'Eye Bolt',
            'part_section' => '',
            'purchase_price' => '65000',
            'total' => '130000',
            'sales_price' => '125000',
            'extended_price' => '250000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME702232',
            'part_description' => 'Eye Bolt',
            'part_section' => '',
            'purchase_price' => '102000',
            'total' => '102000',
            'sales_price' => '214000',
            'extended_price' => '214000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME224981',
            'part_description' => 'Tube Fuel Line',
            'part_section' => '',
            'purchase_price' => '99000',
            'total' => '99000',
            'sales_price' => '330000',
            'extended_price' => '330000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => 'MH037087',
            'part_description' => 'Eye Bolt',
            'part_section' => '',
            'purchase_price' => '130000',
            'total' => '260000',
            'sales_price' => '450000',
            'extended_price' => '900000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME016894',
            'part_description' => 'Plug Fuel Filter',
            'part_section' => '',
            'purchase_price' => '19000',
            'total' => '19000',
            'sales_price' => '64000',
            'extended_price' => '64000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'MH035067',
            'part_description' => 'Gasket Fuel Filter',
            'part_section' => '',
            'purchase_price' => '14000',
            'total' => '14000',
            'sales_price' => '45000',
            'extended_price' => '45000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME736958',
            'part_description' => 'Valve Injection Pump Body (Over Flow)',
            'part_section' => '',
            'purchase_price' => '829500',
            'total' => '829500',
            'sales_price' => '1200000',
            'extended_price' => '1200000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => 'ME728997',
            'part_description' => 'Spring Injection Pump Cover',
            'part_section' => '',
            'purchase_price' => '78000',
            'total' => '156000',
            'sales_price' => '130000',
            'extended_price' => '260000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => 'MH000999',
            'part_description' => 'Bolt Engine Control',
            'part_section' => '',
            'purchase_price' => '27000',
            'total' => '54000',
            'sales_price' => '82000',
            'extended_price' => '164000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME418239',
            'part_description' => 'Cap Assy',
            'part_section' => '',
            'purchase_price' => '459000',
            'total' => '459000',
            'sales_price' => '620000',
            'extended_price' => '620000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME226396',
            'part_description' => 'Insulator Ex manifold',
            'part_section' => '',
            'purchase_price' => '1650000',
            'total' => '1650000',
            'sales_price' => '1950000',
            'extended_price' => '1950000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'MH000703',
            'part_description' => 'Bolt Alternator',
            'part_section' => '',
            'purchase_price' => '119000',
            'total' => '119000',
            'sales_price' => '250000',
            'extended_price' => '250000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'MF434106',
            'part_description' => 'Nut Alternator',
            'part_section' => '',
            'purchase_price' => '19000',
            'total' => '19000',
            'sales_price' => '',
            'extended_price' => '',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME226063',
            'part_description' => 'Bracket Acc Cable',
            'part_section' => '',
            'purchase_price' => '138000',
            'total' => '138000',
            'sales_price' => '215000',
            'extended_price' => '215000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME229404',
            'part_description' => 'Tube T/C Oil Return',
            'part_section' => '',
            'purchase_price' => '164000',
            'total' => '164000',
            'sales_price' => '320000',
            'extended_price' => '320000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '4',
            'uom' => 'ea',
            'part_number' => 'MS660163',
            'part_description' => 'Clip, Recker Cove',
            'part_section' => '',
            'purchase_price' => '13100',
            'total' => '52400',
            'sales_price' => '33000',
            'extended_price' => '132000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => 'MF240033',
            'part_description' => 'Bolt Vacum Pump',
            'part_section' => '',
            'purchase_price' => '5200',
            'total' => '10400',
            'sales_price' => '60000',
            'extended_price' => '120000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME014387',
            'part_description' => 'Hose Engine Breather',
            'part_section' => '',
            'purchase_price' => '162000',
            'total' => '162000',
            'sales_price' => '385000',
            'extended_price' => '385000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'MH021352',
            'part_description' => 'Clip Engine Breather',
            'part_section' => '',
            'purchase_price' => '55000',
            'total' => '55000',
            'sales_price' => '96000',
            'extended_price' => '96000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME012490',
            'part_description' => 'Gasket Front Plate',
            'part_section' => '',
            'purchase_price' => '228000',
            'total' => '228000',
            'sales_price' => '340000',
            'extended_price' => '340000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '4',
            'uom' => 'ea',
            'part_number' => 'MH020777',
            'part_description' => 'Clamp Fuel',
            'part_section' => '',
            'purchase_price' => '45400',
            'total' => '181600',
            'sales_price' => '80000',
            'extended_price' => '320000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => 'MH000392',
            'part_description' => 'Bolt Ex Manifold',
            'part_section' => '',
            'purchase_price' => '33000',
            'total' => '66000',
            'sales_price' => '75000',
            'extended_price' => '150000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => 'MH001216',
            'part_description' => 'Bolt Flywheel',
            'part_section' => '',
            'purchase_price' => '390000',
            'total' => '780000',
            'sales_price' => '75000',
            'extended_price' => '150000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '6',
            'uom' => 'ea',
            'part_number' => 'ME352431',
            'part_description' => 'Clamp FIP Tube',
            'part_section' => '',
            'purchase_price' => '48000',
            'total' => '288000',
            'sales_price' => '73000',
            'extended_price' => '438000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'MF241233',
            'part_description' => 'Bolt Clamp',
            'part_section' => '',
            'purchase_price' => '38000',
            'total' => '38000',
            'sales_price' => '68000',
            'extended_price' => '68000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '3',
            'uom' => 'ea',
            'part_number' => 'ME017147/ME558720',
            'part_description' => 'Tapped Valve',
            'part_section' => '',
            'purchase_price' => '797900',
            'total' => '2393700',
            'sales_price' => '980000',
            'extended_price' => '2940000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '3',
            'uom' => 'ea',
            'part_number' => 'MF450404',
            'part_description' => 'Washer',
            'part_section' => '',
            'purchase_price' => '7575',
            'total' => '22725',
            'sales_price' => '12500',
            'extended_price' => '37500',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => 'MS642596',
            'part_description' => 'Hose Fuel Return',
            'part_section' => '',
            'purchase_price' => '717100',
            'total' => '1434200',
            'sales_price' => '940000',
            'extended_price' => '1880000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME224982',
            'part_description' => 'Tube Injection',
            'part_section' => '',
            'purchase_price' => '98980',
            'total' => '98980',
            'sales_price' => '180000',
            'extended_price' => '180000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '4',
            'uom' => 'ea',
            'part_number' => 'MF434104',
            'part_description' => 'Nut',
            'part_section' => '',
            'purchase_price' => '1818',
            'total' => '7272',
            'sales_price' => '5500',
            'extended_price' => '22000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => '',
            'part_description' => '2nd Engine Block',
            'part_section' => '',
            'purchase_price' => '9300000',
            'total' => '9300000',
            'sales_price' => '13560000',
            'extended_price' => '13560000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => 'ME400662',
            'part_description' => 'Bracket Exhaust Manifold',
            'part_section' => '',
            'purchase_price' => '0',
            'total' => '0',
            'sales_price' => '320000',
            'extended_price' => '320000',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'ea',
            'part_number' => '',
            'part_description' => 'Hose Pump',
            'part_section' => '',
            'purchase_price' => '0',
            'total' => '0',
            'sales_price' => '1638500',
            'extended_price' => '1638500',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => '',
            'part_description' => 'Hose lines',
            'part_section' => '',
            'purchase_price' => '0',
            'total' => '0',
            'sales_price' => '112718',
            'extended_price' => '225436',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '2',
            'uom' => 'ea',
            'part_number' => '',
            'part_description' => 'Clamp hose',
            'part_section' => '',
            'purchase_price' => '0',
            'total' => '0',
            'sales_price' => '23730',
            'extended_price' => '47460',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '6',
            'uom' => 'ea',
            'part_number' => '',
            'part_description' => 'Bolt',
            'part_section' => '',
            'purchase_price' => '0',
            'total' => '0',
            'sales_price' => '12458',
            'extended_price' => '74748',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '6',
            'uom' => 'ea',
            'part_number' => '',
            'part_description' => 'Nut',
            'part_section' => '',
            'purchase_price' => '0',
            'total' => '0',
            'sales_price' => '6526',
            'extended_price' => '39156',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '1',
            'uom' => 'set',
            'part_number' => '',
            'part_description' => 'Bushing camshaft',
            'part_section' => '',
            'purchase_price' => '0',
            'total' => '0',
            'sales_price' => '2906925',
            'extended_price' => '2906925',
            'total_manual' => false,
            'extended_manual' => false
        ],
        [
            'qty' => '3',
            'uom' => 'ea',
            'part_number' => 'MF430004',
            'part_description' => 'Nut Clamp',
            'part_section' => '',
            'purchase_price' => '0',
            'total' => '0',
            'sales_price' => '30000',
            'extended_price' => '90000',
            'total_manual' => false,
            'extended_manual' => false
        ]
    ],
    'styles' => [],
    'notes' => []
];
