<?php

// Auto-generated from data Items RTF (part list operator seat).
// User can still edit/add/delete in website; this is baseline seed.

return [
    ['no' => 1, 'category' => '', 'pn' => '', 'item' => 'Air hose', 'purchase_price' => '', 'sales_price' => '50000', 'photo_paths' => []],
    ['no' => 2, 'category' => '', 'pn' => '', 'item' => 'Air Pressure Switch', 'purchase_price' => '', 'sales_price' => '700000', 'photo_paths' => []],
    ['no' => 3, 'category' => 'ISRI', 'pn' => '', 'item' => 'Air Regulator ISRI', 'purchase_price' => '', 'sales_price' => '4700000', 'photo_paths' => []],
    ['no' => 4, 'category' => 'ISRI', 'pn' => '', 'item' => 'Air spring kit ISRI', 'purchase_price' => '', 'sales_price' => '3100000', 'photo_paths' => []],
    ['no' => 5, 'category' => '', 'pn' => '', 'item' => 'Arm Rest', 'purchase_price' => '', 'sales_price' => '650000', 'photo_paths' => []],
    ['no' => 6, 'category' => '', 'pn' => '', 'item' => 'Back a Rest Foam Komatsu', 'purchase_price' => '', 'sales_price' => '1100000', 'photo_paths' => []],
    ['no' => 7, 'category' => '', 'pn' => '', 'item' => 'Back Foam', 'purchase_price' => '', 'sales_price' => '1400000', 'photo_paths' => []],
    ['no' => 8, 'category' => '', 'pn' => '', 'item' => 'Back Plate repair', 'purchase_price' => '', 'sales_price' => '250000', 'photo_paths' => []],
    ['no' => 9, 'category' => '', 'pn' => '', 'item' => 'Back Rest Plate', 'purchase_price' => '', 'sales_price' => '1100000', 'photo_paths' => []],
    ['no' => 10, 'category' => '', 'pn' => '4V8577', 'item' => 'Bearing As', 'purchase_price' => '', 'sales_price' => '365000', 'photo_paths' => []],
    ['no' => 11, 'category' => '', 'pn' => '', 'item' => 'Bearing Kit Swivel', 'purchase_price' => '', 'sales_price' => '1200000', 'photo_paths' => []],
    ['no' => 12, 'category' => '', 'pn' => '', 'item' => 'Belt stopper', 'purchase_price' => '', 'sales_price' => '350000', 'photo_paths' => []],
    ['no' => 13, 'category' => '', 'pn' => '', 'item' => 'Bolt Air Spring', 'purchase_price' => '', 'sales_price' => '145000', 'photo_paths' => []],
    ['no' => 14, 'category' => '', 'pn' => '', 'item' => 'Bolt Kit', 'purchase_price' => '', 'sales_price' => '275000', 'photo_paths' => []],
    ['no' => 15, 'category' => 'CAT', 'pn' => '3573917', 'item' => 'Boot 740 1', 'purchase_price' => '2444000', 'sales_price' => '2090000', 'photo_paths' => []],
    ['no' => 16, 'category' => '', 'pn' => '', 'item' => 'Boot 740 2', 'purchase_price' => '', 'sales_price' => '1980000', 'photo_paths' => []],
    ['no' => 17, 'category' => '', 'pn' => '1927795', 'item' => 'Boot CAT', 'purchase_price' => '', 'sales_price' => '2200000', 'photo_paths' => []],
    ['no' => 18, 'category' => '', 'pn' => '', 'item' => 'Boot SEARS', 'purchase_price' => '', 'sales_price' => '4290000', 'photo_paths' => []],
    ['no' => 19, 'category' => 'CAT', 'pn' => '', 'item' => 'Bottom Plate', 'purchase_price' => '', 'sales_price' => '550000', 'photo_paths' => []],
    ['no' => 20, 'category' => '', 'pn' => '', 'item' => 'Bracket seat Belt 3 Point', 'purchase_price' => '', 'sales_price' => '3600000', 'photo_paths' => []],
    ['no' => 21, 'category' => '', 'pn' => '', 'item' => 'Bushing Scissor', 'purchase_price' => '', 'sales_price' => '935000', 'photo_paths' => []],
    ['no' => 22, 'category' => 'ISRI', 'pn' => '928474-80/00E', 'item' => 'Air Valve for ISRI', 'purchase_price' => '', 'sales_price' => '2004220', 'photo_paths' => []],
    ['no' => 23, 'category' => 'KAB', 'pn' => '192161', 'item' => 'Cable Tilt KAB', 'purchase_price' => '', 'sales_price' => '1450000', 'photo_paths' => []],
    ['no' => 24, 'category' => '', 'pn' => '4882137', 'item' => 'CAT Tilt for Sears', 'purchase_price' => '', 'sales_price' => '9130000', 'photo_paths' => []],
    ['no' => 25, 'category' => '', 'pn' => '', 'item' => 'Clotch GP', 'purchase_price' => '', 'sales_price' => '450000', 'photo_paths' => []],
    ['no' => 26, 'category' => '', 'pn' => '', 'item' => 'connector', 'purchase_price' => '', 'sales_price' => '105000', 'photo_paths' => []],
    ['no' => 27, 'category' => '', 'pn' => '', 'item' => 'cover front', 'purchase_price' => '', 'sales_price' => '250000', 'photo_paths' => []],
    ['no' => 28, 'category' => '', 'pn' => '', 'item' => 'Cover Hand rest', 'purchase_price' => '', 'sales_price' => '150000', 'photo_paths' => []],
    ['no' => 29, 'category' => '', 'pn' => '', 'item' => 'Cover handle Tilt', 'purchase_price' => '', 'sales_price' => '250000', 'photo_paths' => []],
    ['no' => 30, 'category' => '', 'pn' => '', 'item' => 'Cover rear', 'purchase_price' => '', 'sales_price' => '300000', 'photo_paths' => []],
    ['no' => 31, 'category' => '', 'pn' => '', 'item' => 'Cover Rear Komatsu', 'purchase_price' => '', 'sales_price' => '750000', 'photo_paths' => []],
    ['no' => 32, 'category' => '', 'pn' => '', 'item' => 'Cover Seat Belt', 'purchase_price' => '', 'sales_price' => '1850000', 'photo_paths' => []],
    ['no' => 33, 'category' => '', 'pn' => '', 'item' => 'Cushion As Back Assembly', 'purchase_price' => '', 'sales_price' => '2200000', 'photo_paths' => []],
    ['no' => 34, 'category' => '', 'pn' => '', 'item' => 'Cushion As Pan', 'purchase_price' => '', 'sales_price' => '1700000', 'photo_paths' => []],
    ['no' => 35, 'category' => '', 'pn' => '', 'item' => 'Cushion As Seat', 'purchase_price' => '', 'sales_price' => '1750000', 'photo_paths' => []],
    ['no' => 36, 'category' => 'CAT', 'pn' => '', 'item' => 'Cushion Pan Assy', 'purchase_price' => '', 'sales_price' => '3000000', 'photo_paths' => []],
    ['no' => 37, 'category' => 'KAB', 'pn' => '', 'item' => 'Damper KAB (Volvo)', 'purchase_price' => '', 'sales_price' => '2400000', 'photo_paths' => []],
    ['no' => 38, 'category' => 'CAT', 'pn' => '', 'item' => 'Damper Kit CAT', 'purchase_price' => '', 'sales_price' => '5750000', 'photo_paths' => []],
    ['no' => 39, 'category' => 'ISRI', 'pn' => '20443547 (Volvo)', 'item' => 'Damper kit ISRI', 'purchase_price' => '', 'sales_price' => '7200000', 'photo_paths' => []],
    ['no' => 40, 'category' => '', 'pn' => '', 'item' => 'Damper kit SEARS', 'purchase_price' => '', 'sales_price' => '9900000', 'photo_paths' => []],
    ['no' => 41, 'category' => '', 'pn' => '169546', 'item' => 'Damper Komatsu', 'purchase_price' => '', 'sales_price' => '1600000', 'photo_paths' => []],
    ['no' => 42, 'category' => '', 'pn' => '', 'item' => 'Elbow', 'purchase_price' => '', 'sales_price' => '260000', 'photo_paths' => []],
    ['no' => 43, 'category' => '', 'pn' => '', 'item' => 'Extention plate for 3 point', 'purchase_price' => '', 'sales_price' => '2200000', 'photo_paths' => []],
    ['no' => 44, 'category' => '', 'pn' => '', 'item' => 'Fabricate Stand', 'purchase_price' => '', 'sales_price' => '1000000', 'photo_paths' => []],
    ['no' => 45, 'category' => '', 'pn' => '', 'item' => 'Fitting', 'purchase_price' => '', 'sales_price' => '265000', 'photo_paths' => []],
    ['no' => 46, 'category' => '', 'pn' => '', 'item' => 'Frame Arm Assy', 'purchase_price' => '', 'sales_price' => '1100000', 'photo_paths' => []],
    ['no' => 47, 'category' => '', 'pn' => '', 'item' => 'Frame Suspension', 'purchase_price' => '', 'sales_price' => '3500000', 'photo_paths' => []],
    ['no' => 48, 'category' => '', 'pn' => '', 'item' => 'General air compressor', 'purchase_price' => '', 'sales_price' => '7800000', 'photo_paths' => []],
    ['no' => 49, 'category' => '', 'pn' => '', 'item' => 'Hand Rest', 'purchase_price' => '', 'sales_price' => '1350000', 'photo_paths' => []],
    ['no' => 50, 'category' => '', 'pn' => '', 'item' => 'Handle slidder', 'purchase_price' => '', 'sales_price' => '450000', 'photo_paths' => []],
    ['no' => 51, 'category' => '', 'pn' => '', 'item' => 'Handle Tilt CAT', 'purchase_price' => '', 'sales_price' => '1015000', 'photo_paths' => []],
    ['no' => 52, 'category' => '', 'pn' => '', 'item' => 'Head Rest 1', 'purchase_price' => '', 'sales_price' => '1300000', 'photo_paths' => []],
    ['no' => 53, 'category' => '', 'pn' => '', 'item' => 'Head Rest 2', 'purchase_price' => '', 'sales_price' => '450000', 'photo_paths' => []],
    ['no' => 54, 'category' => '', 'pn' => '', 'item' => 'Head Rest 3', 'purchase_price' => '', 'sales_price' => '1500000', 'photo_paths' => []],
    ['no' => 55, 'category' => 'CAT', 'pn' => '', 'item' => 'Head Rest 4', 'purchase_price' => '', 'sales_price' => '250000', 'photo_paths' => []],
    ['no' => 56, 'category' => 'KAB', 'pn' => '', 'item' => 'High Riser Kit KAB', 'purchase_price' => '', 'sales_price' => '2100000', 'photo_paths' => []],
    ['no' => 57, 'category' => '', 'pn' => '', 'item' => 'KAB for seat Dozer', 'purchase_price' => '', 'sales_price' => '15000000', 'photo_paths' => []],
    ['no' => 58, 'category' => '', 'pn' => '1927799, 2435692, 2435692', 'item' => 'Kit Air Valve', 'purchase_price' => '', 'sales_price' => '2310000', 'photo_paths' => []],
    ['no' => 59, 'category' => 'KAB', 'pn' => '174429', 'item' => 'Kit Air Valve KAB', 'purchase_price' => '', 'sales_price' => '2750000', 'photo_paths' => []],
    ['no' => 60, 'category' => 'CAT', 'pn' => '', 'item' => 'Kit Riser', 'purchase_price' => '', 'sales_price' => '3520000', 'photo_paths' => []],
    ['no' => 61, 'category' => 'CAT', 'pn' => '', 'item' => 'Kit Spring', 'purchase_price' => '', 'sales_price' => '1925000', 'photo_paths' => []],
    ['no' => 62, 'category' => '', 'pn' => '', 'item' => 'Kit Spring', 'purchase_price' => '', 'sales_price' => '1925000', 'photo_paths' => []],
    ['no' => 63, 'category' => '', 'pn' => '164817', 'item' => 'Knob 100/800 Series', 'purchase_price' => '', 'sales_price' => '2100000', 'photo_paths' => []],
    ['no' => 64, 'category' => 'ISRI', 'pn' => '', 'item' => 'Knob ISRI', 'purchase_price' => '', 'sales_price' => '1750000', 'photo_paths' => []],
    ['no' => 65, 'category' => '', 'pn' => '164132, 159099, 1644883', 'item' => 'Knob Lumbar', 'purchase_price' => '', 'sales_price' => '505000', 'photo_paths' => []],
    ['no' => 66, 'category' => '', 'pn' => '2177933', 'item' => 'Latch', 'purchase_price' => '', 'sales_price' => '766000', 'photo_paths' => []],
    ['no' => 67, 'category' => '', 'pn' => '', 'item' => 'Latch Spring', 'purchase_price' => '', 'sales_price' => '341000', 'photo_paths' => []],
    ['no' => 68, 'category' => 'ISRI', 'pn' => '', 'item' => 'Leveling kit ISRI', 'purchase_price' => '', 'sales_price' => '3100000', 'photo_paths' => []],
    ['no' => 69, 'category' => '', 'pn' => '', 'item' => 'Linkage kit', 'purchase_price' => '', 'sales_price' => '550000', 'photo_paths' => []],
    ['no' => 70, 'category' => '', 'pn' => '', 'item' => 'Lock Plate Bottom Boot', 'purchase_price' => '', 'sales_price' => '550000', 'photo_paths' => []],
    ['no' => 71, 'category' => '', 'pn' => '', 'item' => 'Lower Foam', 'purchase_price' => '', 'sales_price' => '1350000', 'photo_paths' => []],
    ['no' => 72, 'category' => '', 'pn' => '', 'item' => 'Misc', 'purchase_price' => '', 'sales_price' => '750000', 'photo_paths' => []],
    ['no' => 73, 'category' => '', 'pn' => '', 'item' => 'Mounting Bolts', 'purchase_price' => '', 'sales_price' => '450000', 'photo_paths' => []],
    ['no' => 74, 'category' => '', 'pn' => '', 'item' => 'Pan As Back', 'purchase_price' => '', 'sales_price' => '2500000', 'photo_paths' => []],
    ['no' => 75, 'category' => '', 'pn' => '', 'item' => 'Pan As Lower', 'purchase_price' => '', 'sales_price' => '3500000', 'photo_paths' => []],
    ['no' => 76, 'category' => '', 'pn' => '', 'item' => 'Pin Suspension', 'purchase_price' => '', 'sales_price' => '200000', 'photo_paths' => []],
    ['no' => 77, 'category' => '', 'pn' => '', 'item' => 'Plat Strip 1mm', 'purchase_price' => '', 'sales_price' => '', 'photo_paths' => []],
    ['no' => 78, 'category' => '', 'pn' => '', 'item' => 'Plate Boot', 'purchase_price' => '', 'sales_price' => '1550000', 'photo_paths' => []],
    ['no' => 79, 'category' => '', 'pn' => '', 'item' => 'Plywood 10mm', 'purchase_price' => '', 'sales_price' => '150000', 'photo_paths' => []],
    ['no' => 80, 'category' => '', 'pn' => '', 'item' => 'Rear Cover adapter for 3 point', 'purchase_price' => '', 'sales_price' => '2200000', 'photo_paths' => []],
    ['no' => 81, 'category' => '', 'pn' => '', 'item' => 'Rear Cover adapter for 3 point', 'purchase_price' => '', 'sales_price' => '2200000', 'photo_paths' => []],
    ['no' => 82, 'category' => '', 'pn' => '', 'item' => 'Recover Hand Rest', 'purchase_price' => '', 'sales_price' => '250000', 'photo_paths' => []],
    ['no' => 83, 'category' => '', 'pn' => '', 'item' => 'Reel Kit', 'purchase_price' => '', 'sales_price' => '1500000', 'photo_paths' => []],
    ['no' => 84, 'category' => '', 'pn' => '', 'item' => 'Relay', 'purchase_price' => '', 'sales_price' => '650000', 'photo_paths' => []],
    ['no' => 85, 'category' => '', 'pn' => '', 'item' => 'Repair Cushion', 'purchase_price' => '', 'sales_price' => '750000', 'photo_paths' => []],
    ['no' => 86, 'category' => '', 'pn' => '', 'item' => 'Repair Cushion as Back', 'purchase_price' => '', 'sales_price' => '450000', 'photo_paths' => []],
    ['no' => 87, 'category' => '', 'pn' => '', 'item' => 'Repair Cushion as Back', 'purchase_price' => '', 'sales_price' => '750000', 'photo_paths' => []],
    ['no' => 88, 'category' => 'CAT', 'pn' => '', 'item' => 'Repair foam', 'purchase_price' => '', 'sales_price' => '250000', 'photo_paths' => []],
    ['no' => 89, 'category' => 'CAT', 'pn' => '', 'item' => 'Repair Foam Manhaul', 'purchase_price' => '', 'sales_price' => '', 'photo_paths' => []],
    ['no' => 90, 'category' => 'CAT', 'pn' => '', 'item' => 'Repair frame', 'purchase_price' => '', 'sales_price' => '750000', 'photo_paths' => []],
    ['no' => 91, 'category' => '', 'pn' => '', 'item' => 'Repair Frame and Pan As', 'purchase_price' => '', 'sales_price' => '1650000', 'photo_paths' => []],
    ['no' => 92, 'category' => '', 'pn' => '', 'item' => 'Repair Frame Manhaul', 'purchase_price' => '', 'sales_price' => '', 'photo_paths' => []],
    ['no' => 93, 'category' => '', 'pn' => '', 'item' => 'Repair Indicator', 'purchase_price' => '', 'sales_price' => '220000', 'photo_paths' => []],
    ['no' => 94, 'category' => 'ISRI', 'pn' => '947519-31/00E', 'item' => 'Switch for ISRI', 'purchase_price' => '', 'sales_price' => '2348809', 'photo_paths' => []],
    ['no' => 95, 'category' => '', 'pn' => '', 'item' => 'Rod', 'purchase_price' => '', 'sales_price' => '495000', 'photo_paths' => []],
    ['no' => 96, 'category' => '', 'pn' => '', 'item' => 'Roller', 'purchase_price' => '121065', 'sales_price' => '132000', 'photo_paths' => []],
    ['no' => 97, 'category' => '', 'pn' => '', 'item' => 'Roller kit', 'purchase_price' => '375405', 'sales_price' => '605000', 'photo_paths' => []],
    ['no' => 98, 'category' => '', 'pn' => '', 'item' => 'Rubber Stopper CAT', 'purchase_price' => '', 'sales_price' => '950000', 'photo_paths' => []],
    ['no' => 99, 'category' => '', 'pn' => '', 'item' => 'Seat Assy', 'purchase_price' => '', 'sales_price' => '10000', 'photo_paths' => []],
    ['no' => 100, 'category' => 'CAT', 'pn' => '', 'item' => 'seat assy 785 komatsu', 'purchase_price' => '', 'sales_price' => '18500000', 'photo_paths' => []],
    ['no' => 101, 'category' => '', 'pn' => '', 'item' => 'Seat Belt', 'purchase_price' => '', 'sales_price' => '1800000', 'photo_paths' => []],
    ['no' => 102, 'category' => 'CAT', 'pn' => '', 'item' => 'Seat Belt 2 Point', 'purchase_price' => '247000', 'sales_price' => '2100000', 'photo_paths' => []],
    ['no' => 103, 'category' => '', 'pn' => '', 'item' => 'Seat Belt 3 Point Black', 'purchase_price' => '', 'sales_price' => '2500000', 'photo_paths' => []],
    ['no' => 104, 'category' => '', 'pn' => '', 'item' => 'Seat Belt 3 Point Komatsu', 'purchase_price' => '', 'sales_price' => '2500000', 'photo_paths' => []],
    ['no' => 105, 'category' => '', 'pn' => '', 'item' => 'Seat Belt 3 Point Manhaul', 'purchase_price' => '', 'sales_price' => '2115000', 'photo_paths' => []],
    ['no' => 106, 'category' => '', 'pn' => '', 'item' => 'Seat Belt 3 point Orange', 'purchase_price' => '', 'sales_price' => '2700000', 'photo_paths' => []],
    ['no' => 107, 'category' => 'CAT', 'pn' => '', 'item' => 'Shaft Scissor', 'purchase_price' => '', 'sales_price' => '946000', 'photo_paths' => []],
    ['no' => 108, 'category' => 'KAB', 'pn' => '160426', 'item' => 'Slide Rail KAB', 'purchase_price' => '', 'sales_price' => '2580400', 'photo_paths' => []],
    ['no' => 109, 'category' => '', 'pn' => '', 'item' => 'Slider Block Kit', 'purchase_price' => '662970', 'sales_price' => '935000', 'photo_paths' => []],
    ['no' => 110, 'category' => '', 'pn' => '', 'item' => 'Slider Kit', 'purchase_price' => '', 'sales_price' => '935000', 'photo_paths' => []],
    ['no' => 111, 'category' => '', 'pn' => '', 'item' => 'Spring 1', 'purchase_price' => '', 'sales_price' => '410000', 'photo_paths' => []],
    ['no' => 112, 'category' => '', 'pn' => '', 'item' => 'Spring 120G', 'purchase_price' => '', 'sales_price' => '120000', 'photo_paths' => []],
    ['no' => 113, 'category' => '', 'pn' => '2365197', 'item' => 'Spring 2', 'purchase_price' => '', 'sales_price' => '1100000', 'photo_paths' => []],
    ['no' => 114, 'category' => '', 'pn' => '1927810', 'item' => 'Spring Assembly air', 'purchase_price' => '2674665', 'sales_price' => '3410000', 'photo_paths' => []],
    ['no' => 115, 'category' => '', 'pn' => '', 'item' => 'Suspension', 'purchase_price' => '', 'sales_price' => '1000000', 'photo_paths' => []],
    ['no' => 116, 'category' => '', 'pn' => '', 'item' => 'suspension as SEARS', 'purchase_price' => '', 'sales_price' => '15000000', 'photo_paths' => []],
    ['no' => 117, 'category' => '', 'pn' => '', 'item' => 'Suspension Assy CAT', 'purchase_price' => '', 'sales_price' => '12500000', 'photo_paths' => []],
    ['no' => 118, 'category' => '', 'pn' => '', 'item' => 'Suspension Assy Komatsu', 'purchase_price' => '', 'sales_price' => '11200000', 'photo_paths' => []],
    ['no' => 119, 'category' => '', 'pn' => '', 'item' => 'Suspension Cover 411', 'purchase_price' => '', 'sales_price' => '2100000', 'photo_paths' => []],
    ['no' => 120, 'category' => 'KAB', 'pn' => '160250', 'item' => 'Suspension Cover KAB 500', 'purchase_price' => '', 'sales_price' => '1811805', 'photo_paths' => []],
    ['no' => 121, 'category' => '', 'pn' => '', 'item' => 'Switch', 'purchase_price' => '', 'sales_price' => '350000', 'photo_paths' => []],
    ['no' => 122, 'category' => 'CAT', 'pn' => '', 'item' => 'Switch ISRI', 'purchase_price' => '', 'sales_price' => '2300000', 'photo_paths' => []],
    ['no' => 123, 'category' => '', 'pn' => '929527-44/00E', 'item' => 'Cable & Knob Height Adjusment', 'purchase_price' => '', 'sales_price' => '2698240', 'photo_paths' => []],
    ['no' => 124, 'category' => '', 'pn' => '', 'item' => 'Swivel bearing', 'purchase_price' => '', 'sales_price' => '2100000', 'photo_paths' => []],
    ['no' => 125, 'category' => '', 'pn' => '', 'item' => 'Tilt Kit Frame', 'purchase_price' => '', 'sales_price' => '2500000', 'photo_paths' => []],
    ['no' => 126, 'category' => 'KAB', 'pn' => '78244', 'item' => 'Tilt Kit Set KAB', 'purchase_price' => '350000', 'sales_price' => '1900000', 'photo_paths' => []],
    ['no' => 127, 'category' => 'Local', 'pn' => '', 'item' => 'Tilt Modification', 'purchase_price' => '', 'sales_price' => '1200000', 'photo_paths' => []],
    ['no' => 128, 'category' => '', 'pn' => '', 'item' => 'Trim Back', 'purchase_price' => '', 'sales_price' => '600000', 'photo_paths' => []],
    ['no' => 129, 'category' => '', 'pn' => '', 'item' => 'Trim seat', 'purchase_price' => '', 'sales_price' => '600000', 'photo_paths' => []],
    ['no' => 130, 'category' => '', 'pn' => '', 'item' => 'Union', 'purchase_price' => '', 'sales_price' => '495000', 'photo_paths' => []],
    ['no' => 131, 'category' => '', 'pn' => '', 'item' => 'Upper plate for slidder', 'purchase_price' => '', 'sales_price' => '1350000', 'photo_paths' => []],
    ['no' => 132, 'category' => '', 'pn' => '160090', 'item' => 'Knob Weight Adjuster', 'purchase_price' => '', 'sales_price' => '1900000', 'photo_paths' => []],
    ['no' => 133, 'category' => 'KAB', 'pn' => '160437', 'item' => 'Weight Adjuster KAB', 'purchase_price' => '', 'sales_price' => '3594165', 'photo_paths' => []],
    ['no' => 134, 'category' => '', 'pn' => '', 'item' => 'Wiring Harness', 'purchase_price' => '', 'sales_price' => '850000', 'photo_paths' => []],
    ['no' => 135, 'category' => '', 'pn' => '914516-05/00E', 'item' => 'Slider Knob', 'purchase_price' => '', 'sales_price' => '1450000', 'photo_paths' => []],
    ['no' => 136, 'category' => '', 'pn' => '921827-02', 'item' => 'swith assy Liebherr', 'purchase_price' => '', 'sales_price' => '9000000', 'photo_paths' => []],
    ['no' => 137, 'category' => 'ISRI', 'pn' => '914868-37/00E', 'item' => 'Knob SET ISRI', 'purchase_price' => '', 'sales_price' => '2200000', 'photo_paths' => []],
    ['no' => 138, 'category' => 'KAB', 'pn' => '164132', 'item' => 'Knob Tilt KAB', 'purchase_price' => '', 'sales_price' => '450000', 'photo_paths' => []],
    ['no' => 139, 'category' => 'KAB', 'pn' => '159099', 'item' => 'Knob Riser KAB', 'purchase_price' => '', 'sales_price' => '450000', 'photo_paths' => []],
    ['no' => 140, 'category' => 'KAB', 'pn' => '175788', 'item' => 'Knob Lumbar KAB', 'purchase_price' => '', 'sales_price' => '450000', 'photo_paths' => []],
    ['no' => 141, 'category' => '', 'pn' => '', 'item' => 'CAT Spring Recliner', 'purchase_price' => '', 'sales_price' => '850000', 'photo_paths' => []],
    ['no' => 142, 'category' => '', 'pn' => '131-5167', 'item' => 'Knob As Dozer CAT', 'purchase_price' => '', 'sales_price' => '2100000', 'photo_paths' => []],
    ['no' => 143, 'category' => '', 'pn' => '', 'item' => 'cover damper volvo', 'purchase_price' => '', 'sales_price' => '1100000', 'photo_paths' => []],
    ['no' => 144, 'category' => '', 'pn' => '3076463', 'item' => 'Indicator Ride Dozer', 'purchase_price' => '', 'sales_price' => '1650000', 'photo_paths' => []],
    ['no' => 145, 'category' => 'KAB', 'pn' => '167564', 'item' => 'Weight Adjuster Kit KAB 800', 'purchase_price' => '', 'sales_price' => '3594165', 'photo_paths' => []],
    ['no' => 146, 'category' => '', 'pn' => '', 'item' => 'Foam', 'purchase_price' => '', 'sales_price' => '850000', 'photo_paths' => []],
    ['no' => 147, 'category' => '', 'pn' => '', 'item' => 'small adapter 3 point seat belt', 'purchase_price' => '', 'sales_price' => '450000', 'photo_paths' => []],
    ['no' => 120, 'category' => 'KAB', 'pn' => '173577', 'item' => 'Suspension Cover KAB 800', 'purchase_price' => '2444000', 'sales_price' => '3150000', 'photo_paths' => []],
    ['no' => 149, 'category' => '', 'pn' => '', 'item' => 'Bolt Pivot CAT', 'purchase_price' => '', 'sales_price' => '475000', 'photo_paths' => []],
    ['no' => 150, 'category' => 'ISRI', 'pn' => '515-31537', 'item' => 'Spring for ISRI Adjustment', 'purchase_price' => '', 'sales_price' => '1100000', 'photo_paths' => []],
    ['no' => 151, 'category' => 'ISRI', 'pn' => '32629-02/00E', 'item' => 'Cable for ISRI Back Adjusment', 'purchase_price' => '', 'sales_price' => '2570000', 'photo_paths' => []],
    ['no' => 152, 'category' => 'ISRI', 'pn' => '914514-01', 'item' => 'High Valve Air ISRI', 'purchase_price' => '', 'sales_price' => '2100000', 'photo_paths' => []],
    ['no' => 153, 'category' => '', 'pn' => '95486-04', 'item' => 'Height Adjusment Cylinder', 'purchase_price' => '', 'sales_price' => '1900000', 'photo_paths' => []],
    ['no' => 154, 'category' => 'ISRI', 'pn' => '91505-01', 'item' => 'Valve Shuttle ISRI', 'purchase_price' => '', 'sales_price' => '1200000', 'photo_paths' => []],
    ['no' => 155, 'category' => 'ISRI', 'pn' => '', 'item' => 'Suspension Cover ISRI', 'purchase_price' => '', 'sales_price' => '2100000', 'photo_paths' => []],
    ['no' => 156, 'category' => 'ISRI', 'pn' => '', 'item' => 'Slider Kit ISRI', 'purchase_price' => '', 'sales_price' => '2580400', 'photo_paths' => []],
    ['no' => 157, 'category' => 'ISRI', 'pn' => '914514-04', 'item' => 'Valve Quit ISRI', 'purchase_price' => '', 'sales_price' => '1250000', 'photo_paths' => []],
    ['no' => 158, 'category' => '', 'pn' => '', 'item' => 'Headrest Guides', 'purchase_price' => '', 'sales_price' => '125000', 'photo_paths' => []],
    ['no' => 159, 'category' => '', 'pn' => '', 'item' => 'seat Belt Volvo', 'purchase_price' => '', 'sales_price' => '1000000', 'photo_paths' => []],
    ['no' => 160, 'category' => '', 'pn' => '', 'item' => 'plate tilt CAT', 'purchase_price' => '', 'sales_price' => '950000', 'photo_paths' => []],
    ['no' => 161, 'category' => '', 'pn' => '', 'item' => 'Buckle seat Belt CAT', 'purchase_price' => '', 'sales_price' => '750000', 'photo_paths' => []],
    ['no' => 162, 'category' => '', 'pn' => '', 'item' => 'Damper CAT Dozer', 'purchase_price' => '', 'sales_price' => '1250000', 'photo_paths' => []],
    ['no' => 164, 'category' => 'ISRI', 'pn' => 'IS.905900', 'item' => 'ISRI Backrest Adjustment Complete front 575', 'purchase_price' => '', 'sales_price' => '6800000', 'photo_paths' => []],
    ['no' => 165, 'category' => 'ISRI', 'pn' => 'IS.845400', 'item' => 'ISRI Handle', 'purchase_price' => '', 'sales_price' => '2345000', 'photo_paths' => []],
    ['no' => 166, 'category' => '', 'pn' => '', 'item' => 'Kit Latch CAT', 'purchase_price' => '', 'sales_price' => '2450000', 'photo_paths' => []],
    ['no' => 167, 'category' => '', 'pn' => '', 'item' => 'hand rest set for Dozer', 'purchase_price' => '', 'sales_price' => '1200000', 'photo_paths' => []],
    ['no' => 168, 'category' => '', 'pn' => '', 'item' => 'Follower Kit', 'purchase_price' => '', 'sales_price' => '2450000', 'photo_paths' => []],
    ['no' => 169, 'category' => '', 'pn' => '', 'item' => 'Recliner gear', 'purchase_price' => '', 'sales_price' => '1950000', 'photo_paths' => []],
    ['no' => 170, 'category' => '', 'pn' => 'SA34900', 'item' => 'Lumbar Kit', 'purchase_price' => '', 'sales_price' => '2750000', 'photo_paths' => []],
    ['no' => 171, 'category' => '', 'pn' => '', 'item' => 'Air Spring Grammer', 'purchase_price' => '', 'sales_price' => '4850000', 'photo_paths' => []],
    ['no' => 172, 'category' => '', 'pn' => '', 'item' => 'Bolt and Nut Kit Riser', 'purchase_price' => '', 'sales_price' => '750000', 'photo_paths' => []],
    ['no' => 173, 'category' => '', 'pn' => '1269890', 'item' => 'Suspension Cover Grammer MSG97', 'purchase_price' => '', 'sales_price' => '6500000', 'photo_paths' => []],
    ['no' => 174, 'category' => '', 'pn' => '1173368', 'item' => 'Air Valve Kit Grammer MSG97', 'purchase_price' => '', 'sales_price' => '9000000', 'photo_paths' => []],
    ['no' => 175, 'category' => '', 'pn' => '1271934/1268387', 'item' => 'Switch Kit Grammer MSG97', 'purchase_price' => '', 'sales_price' => '5800000', 'photo_paths' => []],
    ['no' => 176, 'category' => '', 'pn' => '7M7219', 'item' => 'Thrust Bearing', 'purchase_price' => '92000', 'sales_price' => '175000', 'photo_paths' => []],
    ['no' => 177, 'category' => 'ISRI', 'pn' => 'IS.840190', 'item' => 'ISRI Gas Spring 4004', 'purchase_price' => '5571903', 'sales_price' => '7400000', 'photo_paths' => []],
    ['no' => 178, 'category' => 'ISRI', 'pn' => '41933A', 'item' => 'ISRI Spring 16,6 cm', 'purchase_price' => '1783153', 'sales_price' => '2760000', 'photo_paths' => []],
    ['no' => 179, 'category' => 'ISRI', 'pn' => '30177/00E', 'item' => 'ISRI Shock Absorber', 'purchase_price' => '3725653', 'sales_price' => '4950000', 'photo_paths' => []],
    ['no' => 180, 'category' => '', 'pn' => '132-146', 'item' => 'Grammer Air Handle With Switch', 'purchase_price' => '1781333', 'sales_price' => '2650000', 'photo_paths' => []],
    ['no' => 181, 'category' => '', 'pn' => '', 'item' => 'Repair Gear recliner CAT', 'purchase_price' => '', 'sales_price' => '1850000', 'photo_paths' => []],
    ['no' => 182, 'category' => '', 'pn' => '', 'item' => 'Safety guard air valve', 'purchase_price' => '', 'sales_price' => '450000', 'photo_paths' => []],
    ['no' => 183, 'category' => '', 'pn' => '1201989', 'item' => 'Gammer Switch Kit', 'purchase_price' => '', 'sales_price' => '6800000', 'photo_paths' => []],
    ['no' => 184, 'category' => '', 'pn' => '', 'item' => 'Back plate D85', 'purchase_price' => '', 'sales_price' => '750000', 'photo_paths' => []],
    ['no' => 185, 'category' => '', 'pn' => '', 'item' => 'Bottom plate D85', 'purchase_price' => '', 'sales_price' => '750000', 'photo_paths' => []],
];
