<?php

/**
 * Datalists khusus template Engine Triton LV-R157 (All New Triton HDX-H MT) (v1).
 * Source-of-truth: folder template (awet & konsisten).
 */

return [
    'uom' => [
        'EA',
        'SET',
        'PCS',
        'PACK',
        'UNIT',
        'LTR',
        'LTRS',
        'MTR',
        'KG',
        'BOX',
        'CAN',
        'ROLL',
        'BOT',
        'PAIR',
    ],

    'part_description' => [
        'Bearing SET, Conrod, STD',
        'Piston & Pin Piston Assy (STD A)',
        'Sleeve Cyl STD 4D56',
        'Bearing Crankshaft',
        'Valve Exhaust',
        'Valve Intake',
        'Seal, Exhaust Valve Item',
        'Disc Clutch',
        'Glow plug',
        'Oil pump',
        'Gasket KIT, Engine Overhaul',
        'Gasket Cylinder Head',
        'Belt, Valve Timing',
        'Gasket Engine Oil Pan',
        'Gasket Rocker Cover',
        'Regulator/Thermostat',
        'Cap Assy Engine Oil Filter',
        'Snap Ring',
        'Oil filter',
        'Hose Triton (Eng Oil CoolerA)',
        'Water Pump',
        'Vacuum pump',
        'Thrust Bearing/Metal Bulan, STD',
        'Ring Piston, STD',
        'Liner',
        'Valve Guide Ex',
        'Valve Guide In',
        'PULLEY IDLER TIMING',
        'TENSIONER,BALANCER TIMING BELT',
        'HOSE ENGINE OIL COOLER WATER FEED',
        'HOSE,VACUUM PUMP OIL RETURN',
        'BOLT COVER VALVE (FLANGE M6X25)',
        'HOSE BREATHER',
        'CLAMP',
        'BOLT DIPSTICK',
        'STUD  8X22',
        'STUD  8X28',
        'MAIN BEARING , STD',
        'BEARING FLY WHEEL',
        'BOLT FLY WHEEL',
        'LOCK VALVE',
        'SPROCKET,INJECTION PUMP',
        'BOLT,ENG FR CASE  (M8X70)',
        'BOLT,ENG FR CASE  (M8X55)',
        'HOSE FUEL',
        'HOSE FUEL RETURN',
        'BRAKET PIPE FUEL',
        'HOSE WATER',
        'PROTECTOR,T/C WATER HOSE',
        'THERMOSTAT',
        'HOSE',
        'PROTECTION HOSE',
        'BOLT INTAKE ( FLANGE M8X45)',
        'NUT INTAKE',
        'NUT TURBO',
        'WASHER',
        'HOSE ASSY,EMISSION VACUUM CONTROL',
        'VALVE EMISSION VACUUM',
        'HOSE AND PIPE ASSY',
        'CAP PLUG',
        'GUARD FLY WHEEL LOWER',
        'BUSHING BALANCER',
        'TENSIONER,',
        'Fuel Filter',
        'Tensioner Bearing Relay panjang',
        'Tensioner Bearing Relay Pendek',
        'Diagram Clucth',
        'Crankshaft',
        'Camshaft IN/EX',
        'Housing Seal Crankshaft',
    ],

    'part_section' => [
        'Update Harga Beli',
        'Belum ada harga jual',
        'Harga beli lebih tinggi',
        'Stock Office',
        'Other',
    ],
];