<?php

return [
  'meta' => [
    'customer' => '',
    'quo_est_number' => '',
    'wo_number' => '',
    'model' => 'ENGINE',
    'sn' => 'N/A',
    'equipt_no' => '',
    'attention' => '',
    'date' => '',
    'smu' => 'N/A',
    'job_outline' => '',
    'sub_total_hours' => '36,00',
    'sub_total_labour' => '10800000',
    'sub_total_parts' => '55386380',
  ],

  'main_rows' => [
    [
      'seg' => '',
      'code' => '',
      'component_desc' => 'PRE-ELIMINARY INSPECTION',
      'work_desc' => 'PERFORM INSPECTION FOR MISSING PARTS',
      'work_order' => '',
      'hours' => '2,00',
      'labour_charge' => '',
      'parts_charge' => '',
    ],
    [
      'seg' => '',
      'code' => '',
      'component_desc' => 'DISASSEMBLY TASK',
      'work_desc' => 'STRIP DOWN ENGINE ASSY',
      'work_order' => '',
      'hours' => '12,00',
      'labour_charge' => '',
      'parts_charge' => '',
    ],
    [
      'seg' => '',
      'code' => '',
      'component_desc' => '',
      'work_desc' => 'CLEAN UP STRIPED COMPONENTS',
      'work_order' => '',
      'hours' => '',
      'labour_charge' => '',
      'parts_charge' => '',
    ],
    [
      'seg' => '',
      'code' => '',
      'component_desc' => '',
      'work_desc' => 'INSPECT AND MEASUREMENT ENGINE COMPONENTS',
      'work_order' => '',
      'hours' => '',
      'labour_charge' => '',
      'parts_charge' => '',
    ],
    [
      'seg' => '',
      'code' => '',
      'component_desc' => 'ASSEMBLY TASK',
      'work_desc' => 'ASSEMBLY ENGINE',
      'work_order' => '',
      'hours' => '16,00',
      'labour_charge' => '',
      'parts_charge' => '',
    ],
    [
      'seg' => '',
      'code' => '',
      'component_desc' => 'COMPLETION TASK',
      'work_desc' => 'START UP AND RUNNING ENGINE, CHECK LEAKS',
      'work_order' => '',
      'hours' => '4,00',
      'labour_charge' => '',
      'parts_charge' => '',
    ],
    [
      'seg' => '',
      'code' => '',
      'component_desc' => '',
      'work_desc' => 'PAINTING ENGINE GP',
      'work_order' => '',
      'hours' => '2,00',
      'labour_charge' => '',
      'parts_charge' => '',
    ],
  ],

  'misc' => [
    'consumable_percent' => '5',
    'consumable_charge' => '540000',
    'painting_total' => '1740000',
    'external_total' => '23250000',
  ],

  'painting_rows' => [
    [
      'item' => 'COLOUR PAINT',
      'qty' => '2',
      'uom' => 'LTRS',
      'unit_price' => '130000',
      'total' => '260000',
    ],
    [
      'item' => 'BLACK PAINT',
      'qty' => '1',
      'uom' => 'LTRS',
      'unit_price' => '130000',
      'total' => '130000',
    ],
    [
      'item' => 'THINNER',
      'qty' => '5',
      'uom' => 'LTRS',
      'unit_price' => '22000',
      'total' => '110000',
    ],
    [
      'item' => 'MASKING TAPE 2"',
      'qty' => '1',
      'uom' => 'EA',
      'unit_price' => '15000',
      'total' => '15000',
    ],
    [
      'item' => 'ENGINE OIL',
      'qty' => '25',
      'uom' => 'LTRS',
      'unit_price' => '45000',
      'total' => '1125000',
    ],
    [
      'item' => 'FUEL',
      'qty' => '10',
      'uom' => 'LTRS',
      'unit_price' => '10000',
      'total' => '100000',
    ],
  ],

  'external_rows' => [
    [
      'service' => 'Dinamo Starter Motor Triton',
      'remark' => '',
      'amount' => '',
    ],
    [
      'service' => 'Service Alternator',
      'remark' => '',
      'amount' => '',
    ],
    [
      'service' => 'Callibration FIP & Test 4x Nozzle',
      'remark' => '',
      'amount' => '7500000',
    ],
    [
      'service' => 'Grinding  12 ea Valve',
      'remark' => '',
      'amount' => '750000',
    ],
    [
      'service' => 'replace 4ea Liner and cutting',
      'remark' => '',
      'amount' => '4500000',
    ],
    [
      'service' => 'Install 4x Liner',
      'remark' => '',
      'amount' => '',
    ],
    [
      'service' => 'Polish and Repair Rear Oil Seal Contact Surface Crankshaft',
      'remark' => '',
      'amount' => '1500000',
    ],
    [
      'service' => 'Upper Timing Cover (Repair Crack Rebushing Bolt Hole)',
      'remark' => '',
      'amount' => '650000',
    ],
    [
      'service' => 'Repair Thread Hole (Cyl Head, Cover Valve, Intake Manifold , Cooler EGR)',
      'remark' => '',
      'amount' => '850000',
    ],
    [
      'service' => 'Recondition Turbo charger',
      'remark' => '',
      'amount' => '6500000',
    ],
    [
      'service' => 'Polish Camshaft',
      'remark' => '',
      'amount' => '1000000',
    ],
  ],

  'totals' => [
    'discount_percent' => '2',
    'discount_amount' => '1834328',
    'tax_percent' => '11',
    'sales_tax' => '9887026',
    'total_labour' => '10800000',
    'total_parts' => '55386380',
    'total_misc' => '25530000',
    'total_before_disc' => '91716380',
    'total_before_tax' => '89882052',
    'total_repair_charge' => '99769078',
  ],
];