<?php

/**
 * Datalists khusus template Engine 4V21Y-77263 Euro 4 (v1).
 * Tujuan: dropdown/datalist di worksheet mengikuti istilah di Excel Euro 4.
 */

return [
    // UOM yang umum dipakai di template ini (boleh ditambah nanti)
    'uom' => [
        'EA',
        'SET',
        'PCS',
        'PACK',
        'UNIT',
        'LTR',
        'LTRS',
        'MTR',
        'KG',
        'BOX',
        'CAN',
        'ROLL',
    ],

    // Part Description (diambil dari defaults_parts Euro 4 v1)
    'part_description' => [
        'Bearing set crankshaft (5 Ea)',
        'bearing set conrod (SET-UPR &LWR)',
        'plate crankshaft thrust',
        'Ring piston (4 Ea)',
        'valve tappet',
        'Piston',
        'seal valve stem',
        'oil seal timing gear case',
        'oil seal cranksfat (Rear)',
        'Sleeve Cylinder (Liner) STD',
        'Gasket Rocker Cover',
        'Gasket Rocker D = 50',
        'O - Ring Rocker Cover',
        'Seal Rocker Cover Bolt',
        'Gasket Eng Oil Filler CAP',
        'cap cyliner head D = 12',
        'gasket cylinder head or B Grade',
        'Gasket intake air heater',
        'Gasket Egr Pipe',
        'Gasket exhaust manifold',
        'Gasket T/C',
        'Nut T/C D = 10',
        'O - Ring T/C Nok F 201 ID = 44,4',
        'Gasket EGR Pipe',
        'Gasket T/C Oil Return Tube',
        'Gasket Cooling Water Line',
        'Washer Cooling Water Line',
        'Gasket Eng Oil Line',
        'O-Ring Cooling Water Line',
        'Gasket Thermostat Case To Cyl Head',
        'Gasket Thermostat Cover, O-Ring Water Pump',
        'O-Ring Water Pump',
        'Belt Alternator & Other',
        'seal crankshaft bearing gasket cylinder block',
        'FR Plate',
        'oil slinger cranlshaft',
        'gasket engine oil pan drain plug',
        'O-ring Engine oil filler D = 10.8',
        'gasket timing gear case',
        'bearing flywheel ID = 20',
        'o ring eng oil pump D =21.7',
        'o ring oil strainer D = 21.7',
        'gasket eng oil cooler cover',
        'o ring injection pump D = 140',
        'gasket fuel return line D - 14',
        'o ring vacum pump nok T 667 ID = 75.50 T = 3.10',
        'o ring vacum pump nok T 667 ID = 10.80 T= 2.58',
        'o ring p/s oil pump ',
        'oil Filter',
        'Disc Clutch (Rivet)',
        'Clucth Cover',
        'Snap Ring',
        'oil pan',
        'Oil Pump',
        'Pin Piston',
        'Oil Filter Cap',
        'Valve Guide Intake',
        'Valve Guide Exhaust',
        'Water Pump',
        'Rubber Mounting Engine LH/RH',
        'Plate Flywheel Bolt Lock',
        'Flywheel Assy FE75M All 2nd Parts',
        'Hose Cooling Water Line',
        'Bolt Clutch Cover',
        'Filter Oil',
        'Seal klep Stem',
        'Exhaust Gas/Cooler EGR',
        'Packing Oil Cooler',
        'Seal Cup',
        'Fan Blade',
        'Thermostat',
    ],

    // Part Section (dipakai untuk dropdown Part Section)
    'part_section' => [
        'Update Harga Beli',
        'Belum ada harga jual',
        'Harga beli lebih tinggi',
        'Stock Office',
        'Other',
    ],

];
